# Generated by Django 4.2.2 on 2023-07-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Тэг')),
                ('importance', models.CharField(max_length=25, unique=True, verbose_name='Важность')),
                ('slug', models.CharField(max_length=25, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': ('Тэг',),
                'verbose_name_plural': ('Тэги',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задания')),
                ('description', models.TextField(max_length=500, verbose_name='Описание задания')),
                ('image', models.ImageField(upload_to='tasks/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_completed', models.BooleanField(verbose_name='Статус выполнения')),
            ],
        ),
    ]
