# Generated by Django 4.2.2 on 2023-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tag_importance_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to='tasks/', verbose_name='Изображение'),
        ),
    ]
